name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.x"
          cache: true

      # 关键一步：在 pub get 前将 pubspec.yaml 里的 intl 版本限制解绑，彻底消除死锁冲突
      - name: Unlock intl dependency version
        run: |
          cd simple_live_app
          sed -i 's/intl: \^0.20.2/intl: any/g' pubspec.yaml

      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --no-tree-shake-icons --android-skip-build-dependency-validation

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: simple_live_app/build/app/outputs/flutter-apk/*.apk
